### ISSUE TITLE
GCM REGISTRATION_ID for Textsecure server 

### ISSUE THREAD

**Issue by amatanat** [skal1ozz/RedPhoneServer#1]
Hello,

I'm trying to run my own textsecure server, without redphone.  Could you please write steps how can I get REGISTRATION_ID from google developer console?

**Comment by akillthegod** [comment]
REGISTRATION_ID:
1. You need to pay google dev account and get here https://console.developers.google.com/home/
2. Then create new project, like Default Demo App and Project Number is REGISTRATION_ID
I guess. 
Anyway, i have write this my number.

But i can't normally connect my app to server. While connecting, it gets error
https://groups.google.com/forum/#!topic/whispersystems-community-unofficial/_tLBJBRD_w8

**Comment by amatanat** [comment]
I'm getting the same error. I think Project Number is not REGISTRATION_ID. See the link below.

http://docs.aws.amazon.com/sns/latest/dg/mobile-push-gcm.html#registration-id-gcm

**Comment by skal1ozz** [comment]
> REGISTRATION_ID:
> 1. You need to pay google dev account and get here https://console.developers.google.com/home/
> 2. Then create new project, like Default Demo App and Project Number is REGISTRATION_ID

Yes, this is correct.

> But i can't normally connect my app to server. While connecting, it gets error

You're receiving this error because you didn't set the authKey for RedPhone in the config.yml file.
For example:

redphone:
    authKey: 1029384756

**Comment by amatanat** [comment]
You are right, Project number - senderID in local.yml is the REGISTRATION_ID. I think they just gave wrong name to this variable. 

 I'm not sure about redphone authKey. Because when server runs it doesn't give error that  you should assign redphone authKey. Why do you think this is the problem? and how can I get redphone authKey?

**Comment by akillthegod** [comment]
> You're receiving this error because you didn't set the authKey for RedPhone in the config.yml file.
> For example:
> 
> redphone:
> authKey: 1029384756

So. We need to install RedPhone Server, right?
And, how we can do that? Could you write any instruction with link to reccomended by you RedPhone Server repo?

**Comment by amatanat** [comment]
Finally, my device connected to my server! 

What I did: commented "createaccount" method for redphone in RedPhoneAccountManager.java and references to this method.

**Comment by akillthegod** [comment]
> Finally, my device connected to my server!
> 
> What I did: commented "createaccount" method for redphone in RedPhoneAccountManager.java and references to this method.

So, and I'm too. But I have got an error, when tring sent encoded message;

TexSecure terminal
org.whispersystems.textsecuregcm.entities.EncryptedOutgoingMessage: Invalid Key

**Comment by skal1ozz** [comment]
> So. We need to install RedPhone Server, right?
> And, how we can do that? Could you write any instruction with link to reccomended by you RedPhone Server repo?

No. You should enter the authKey for it and that's it.

> What I did: commented "createaccount" method for redphone in RedPhoneAccountManager.java and references to this method.

It's not good idea. It would be better to do like i adviced in the installation guide here https://github.com/skal1ozz/RedPhoneServer/blob/master/TextSecure-Server_Installation.txt

Just return 200 ok for all /api/ requests

**Comment by akillthegod** [comment]
> It's not good idea. It would be better to do like i adviced in the installation guide here https://github.com/skal1ozz/RedPhoneServer/blob/master/TextSecure-Server_Installation.txt
> 
> Just return 200 ok for all /api/ requests

But by this way we getting this errors:

TextSecure output: 

```
`"PUT /api/v1/accounts/token/+123456789090:1456965493:10977e29a477a88a7236 HTTP/1.1" 404`
```

Android monitor output:

```
03-03 08:23:48.716 10379-10685/org.thoughtcrime.securesms W/RegistrationService: java.io.IOException: Failed to create account: 404 
at org.thoughtcrime.redphone.signaling.RedPhoneAccountManager.createAccoun
```

Also, what the server are in nginx configure

```
    upstream textserver {
        server 192.168.1.1:8080;
    }
    upstream redphone_master {
        server 192.168.1.2:8080;
```

is it white static ip of VPS server?

**Comment by skal1ozz** [comment]
> `"PUT /api/v1/accounts/token/+123456789090:1456965493:10977e29a477a88a7236 HTTP/1.1" 404`

How can you get 404 if you sending 200ok ?)

And again, you should return for all '/api/' client's requests "200 OK" or "204 OK".
For example in nginx mapping:

```
    location /api {
        return 204;
    }
```

> Also, what the server are in nginx configure

It doesn't matter what Ip your server has. For example, nginx conf based on my settings:

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
upstream textserver {
    server 192.168.2.4:8080;
}
upstream redphone_relay {
    server 192.168.2.4:31337;
}
upstream redphone_master {
    server 192.168.2.4:8880;
}
upstream pushserver {
    server 192.168.2.7:80;
}
server {
listen white.static.ip.address:443 ssl;
    ssl_certificate     /path/to/your/cert.crt;
    ssl_certificate_key /path/to/your/key.key;
    server_name textsecure.example.com;
    location /api {
        #proxy_redirect off;
        #proxy_set_header Host $host;
        #proxy_read_timeout 120;
        #proxy_connect_timeout 120;
        #proxy_set_header X-Real-IP $remote_addr;
        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header X-Forwarded-Protocol $scheme;
        #proxy_pass_request_headers on;
        #proxy_pass http://redphone_master;
        return 204;
    }
    location /v1/websocket/ {
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_read_timeout 120;
        proxy_connect_timeout 120;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_pass http://textserver/v1/websocket/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    location / {
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_read_timeout 120;
        proxy_connect_timeout 120;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_pass http://textserver;
    }
}
```

**Comment by akillthegod** [comment]
Okay. Could you write an letter to akillthegod@gmail.com? Seems we are doing something wrong.

**Comment by skal1ozz** [comment]
> Okay. Could you write an letter to akillthegod@gmail.com? Seems we are doing something wrong.

Have written to your email "Hi")

**Comment by maklei125** [comment]
Does anyone have resolved this issue? I have the same issue and I can't figure out?
/api/v1/accounts/token give me 404

**Comment by AbdullahAlAsad** [comment]
Hi I am not getting gcm push messages when app is on background. from push server log it is saying 404 not found. Any hints.

**Comment by skal1ozz** [comment]
@godslave05 can you give a little bit more information about the error, maybe log from server/client.

**Comment by skal1ozz** [comment]
> Does anyone have resolved this issue? I have the same issue and I can't figure out?
> /api/v1/accounts/token give me 404

@maklei125 it is an error of nginx? What's the method of the request ?
The right request for textsecure is "GET /v1/accounts/token" and only.
But RedPhone request should have additional information in the path -- phone, id and key.
For example:
"GET /v1/accounts/token/+123456789098:1:a94329ra9sas9fa9sfqsa"

So first of all, you should check urls which you handle with nginx.

**Comment by roman921111** [comment]
Thanks for your great resource at first! @skal1ozz 
I have tried to find out full and detailed TextSecure & RedPhone server installation guide, but nothing.

I believe you could help me with this.
And I see Whisper stopped supporting for RedPhone server, then what could I do for secure calling ?
What server could I use for this and could you give me some guides or link?

And in your repo, I never see any code for RedPhone if I need to use old version for secure calling.
hope your help Alex.

**Comment by skal1ozz** [comment]
Hi, @roman921111 ! [Here](https://github.com/lucaconte/RedPhoneServer/tree/f8f91de0d03b18166ce436860bb67f0b1344c1ca) you can find the old code.
Hope that helps.
