### ISSUE TITLE
RedPhoneServer

### ISSUE THREAD

**Issue by lucaconte** [skal1ozz/RedPhoneServer#2]
> Temporarily the repo with custom RedPhone Master server was disabled(it will return)

when? ;-)

I've installed all, I'm in Android debugging mode with my own two servers up and running all is going well BUT not the RedPhone Account registration because I've NO RedPhone server Up&Running. Is It mandatory? Where Can I find a valid implementation?

Anyway, many (and many and many) thanks for your documentation!!!

**Comment by skal1ozz** [comment]
> when? ;-)
> 
> I've installed all, I'm in Android debugging mode with my own two servers up and running all is going well BUT not the RedPhone Account registration because I've NO RedPhone server Up&Running. Is It mandatory? Where Can I find a valid implementation?
> 
> Anyway, many (and many and many) thanks for your documentation!!!

It is nice to know that my documentations have helped you.
RedPhoneServer part code will return in several months, when it will be fully working with relay(TURN) server part.
Thanks.

**Comment by mikelb** [comment]
Can you share the RedPhoneServer code, even if it is without relay(TURN)?

**Comment by maqnouch** [comment]
:+1:

**Comment by skal1ozz** [comment]
> Can you share the RedPhoneServer code, even if it is without relay(TURN)?

[lucaconte has fork](https://github.com/lucaconte/RedPhoneServer) from this repo which has commits with old code you can checkout it and use. It is glitchy and without turn, but works. Hope this helped)

**Comment by techkey** [comment]
Hi, thanks to you Signal Android now register fine. Secure calls are not working yet, I think because my local servers are all IP based instead of named virtual hosts. I'm in the middle of fixing that.  

Just a friendly question, I don't mean to push or anything like that, is there an update on the status of the relay(TURN)? :)

**Comment by skal1ozz** [comment]
> Hi, thanks to you Signal Android now register fine. Secure calls are not working yet, I think because my local servers are all IP based instead of named virtual hosts. I'm in the middle of fixing that.

Hi, nice to hear it) You should remember about certificate validation. You can set top domain name suffix as a blank string and returning an IP of your relay server, but in this case you have to handle CA validation of your certificate.

> Just a friendly question, I don't mean to push or anything like that, is there an update on the status of the relay(TURN)? :)

Unfortunately there is no update for now.

**Comment by techkey** [comment]
Thanks for your reply
