### ISSUE TITLE
Telephony

### ISSUE THREAD

**Issue by usergoodvery** [skal1ozz/RedPhoneServer#3]
hi 
What telephony server is used for red phone?

**Comment by skal1ozz** [comment]
> hi 
> What telephony server is used for red phone?

Hi. What do you mean ?

**Comment by usergoodvery** [comment]
I had assumed they used some kind of standard sip server like kamailio , but now I know they wrote their own thing, which they haven't open sourced.
Are you still hacking on it with Python?

**Comment by skal1ozz** [comment]
> I had assumed they used some kind of standard sip server like kamailio , but now I know they wrote their own thing, which they haven't open sourced.
> Are you still hacking on it with Python?

Indeed.

**Comment by usergoodvery** [comment]
I am considering writing a backend (the protocol layer only) in c. I have an old version of the python implementation browsing through it it doesn't seem to be doing much more than routing packets between the connected devices.
I personally would rather not waste time reverse engineering the phone if somebody else has done it already. Are you going to publish your efforts in that regard?

**Comment by maqnouch** [comment]
Hi @skal1ozz , 
It will be very nice if you publish your work on the Redphone server, so we will have a community around it that will make a serious alternative to the official ones.

**Comment by usergoodvery** [comment]
Hi aqnouch,

Out of interest what are you hoping to achieve with the redphone backend? Just for fun, or you are considering running a proper voip service with it, or perhaps it is just a principles matter? (considering the closed source nature of redphone).
The reason I ask, unless you have a specific interest in the whisper systems products, arguably, there are better softphones out there that work with  standard sip backends.

regards,

**Comment by skal1ozz** [comment]
> I am considering writing a backend (the protocol layer only) in c. 

What protocol layer are you talking about ?

> I have an old version of the python implementation browsing through it it doesn't seem to be doing much more than routing packets between the connected devices.

What have you expected it has to do? Redphone Server works as a TURN server. And TURN server just delivers packets from a source to a destination.

**Comment by maqnouch** [comment]
Hi @usergoodvery ,
I'm considering running a my own voip service based on a fork of the Signal application, and I'm working on the turn server in order to have a working redphone clone server.

**Comment by usergoodvery** [comment]
@skal1ozz What I meant by protocol is the signalling part + whatever framing protocol it used, as I already have my own server environment to manage persistent connections, proxy packets, handle accounts, GCM etc.... 
Having spent sometime on the the android redphone code I can see the signalling part is very thin and they use standard (z)rtp, so it is relatively straightforward to put together.

@aqnouch Thanks for sharing that. Was looking to see if there is avenue to collaborate there. What language/platform are you considering for that?

**Comment by skal1ozz** [comment]
> @skal1ozz What I meant by protocol is the signalling part + whatever framing protocol it used, as I already have my own server environment to manage persistent connections, proxy packets, handle accounts, GCM etc.... 
> Having spent sometime on the the android redphone code I can see the signalling part is very thin and they use standard (z)rtp, so it is relatively straightforward to put together.

As i said above RedPhone server works like TURN and only. [This](https://github.com/lucaconte/RedPhoneServer/tree/f8f91de0d03b18166ce436860bb67f0b1344c1ca) code does everything you need to start calls except relay for UDP.
So if you already have so much stuff it would be no problem for you to make call service.

**Comment by usergoodvery** [comment]
Thanks I get the TURN bit, so no issues proxying udp packets across connected ends... btw the link you provided is broken, but I think I know what that is anyway... I am in the process of rewriting the whole backend thing, as it turns out the redphone client code is not bad as a reference and one can see what needs to happen to get the calls going
